<?php

/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Contributor extends BaseContributor
{
	public static $roles = array('Helper', 'Contributor', 'Developer', 'Lead');

  /**
   * toArray
   *
   * @param      boolean $deep - Return also the relations
   * @return     array
   */
	public function toArray($deep = true, $prefixKey = false)
	{
		$ret = parent::toArray($deep, $prefixKey);
		$ret['url_edit'] = $this->getUrlEdit();
		$ret['role_text'] = $this->getRoleText();
		return $ret;
	}

	/**
	 * getRoleText
	 *
	 * @return     string
	 */
	public function getRoleText() {
		return self::$roles[$this['role']];
	}

	/**
	 * getUrlEdit
	 *
	 * @return     string
	 */
	public function getUrlEdit() {
		return $this->getContext()->getRouting()->gen('resources.resource.contributors.contributor.edit', array(
			'resource' => $this['resource']['ident'],
			'contributor' => $this['id']
		));
	}
}