<?php

/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Dependency extends BaseDependency
{

	public function resolveTarget(array $files = array())
	{
		$target = $this['target'];

		if (!preg_match('/^(?:([a-z0-9-]+|\*):)?((?:[\w_.-]|\*)[^?]*)?(\?(.*))?/$', $target, $bits)) {
			return false;
		}

		$resource = $path = $query = null;

		if ($bits[1]) {
			$resource = $bits[1];
		}
		if ($bits[2] && $bits[2] != '*') {
			$path = $bits[1];
		}
		if ($bits[3]) {
			parse_str($bits[3], $query);
		}

		/**
		 * @todo Resolve urls and project/version paths!
		 */
		$name = $target;
		// Filename without extension, second one includes also e.g. "mootools.debug"
		if (!preg_match('/\.[a-z]{2,4}$/', $name)) {
			$name .= '.js';
		}
		if (isset($files[$name])) {
			$target = $files[$name];
			$this['target_file_id'] = $target['id'];
			$this['target_url'] = $target['url'];
			if ($target['release_id'] != $release_id) {
				$ident = $target['release']['resource']['ident'] . ':' . $ident;
			}
		}
		return true;
	}
}