<?php

/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class File extends BaseFile
{
	public static $roles = array('Text', 'Json', 'Source', 'Source (JS)', 'Asset', 'Test', 'Spec', 'Doc', 'Demo', 'Compatibility', 'Readme', 'Package');

  /**
   * toArray
   *
   * @param      boolean $deep - Return also the relations
   * @return     array
   */
	public function toArray($deep = false, $prefixKey = false)
	{
		$ret = parent::toArray($deep, $prefixKey);
		$ret['role_text'] = $this->getRoleText();
		return $ret;
	}

	/**
	 * getRoleText
	 *
	 * @return     string
	 */
	public function getRoleText() {
		return self::$roles[$this['role']];
	}
}