<?php

/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Hit extends BaseHit
{
	/**
	 * @param 	Doctrine_Event
	 */
	public function postInsert($event)
	{
		$query = Doctrine_Query::create();
		$query->update('Resource')
			->set('hits_count', 'hits_count + 1')
			->where('id = ?', array($this['id']))
			->execute();
	}

	/**
	 * @param 	Doctrine_Event
	 */
	public function postDelete($event)
	{
		$query = Doctrine_Query::create();
		$query->update('Resource')
			->set('hits_count', 'hits_count - 1')
			->where('id = ?', array($this['id']))
			->execute();
	}
}