<?php

/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Licence extends BaseLicence
{
  /**
   * toArray
   *
   * @param      boolean $deep - Return also the relations
   * @return     array
   */
	public function toArray($deep = false, $prefixKey = false)
	{
		return parent::toArray(false, $prefixKey);
	}
}